### ISSUE TITLE
Version 1.0.3 on npm is still using code generated from previous version

### ISSUE THREAD

**Issue by lephuongbg** [pawelgabryelewicz/babel-preset-typescript-vue#4]
File [lib/index.js](https://unpkg.com/browse/babel-preset-typescript-vue@1.0.3/lib/index.js) at line 32 still contains the old code:

```js
if (typeof json.script !== "undefined" && typeof json.script["@_lang"] && json.script["@_lang"].toLowerCase() === "ts") {
  return true;
}
```

while it should be the same with [index.js](https://unpkg.com/browse/babel-preset-typescript-vue@1.0.3/src/index.js):

```js
if(json.script && typeof json.script === "object" && typeof json.script["@_lang"] === "string" && json.script["@_lang"].toLowerCase() === "ts") {
 return true;
}
```

Please issue a new version with the new code. Thanks for this nice plugin.

**Comment by Merott** [comment]
Just spent 2 hours trying to debug an issue, only to find the same issue as @lephuongbg shared here.

Can we please get a new release to fix this?

**Comment by bbugh** [comment]
I documented reproduction steps on the pull request that caused this, in case it matters: https://github.com/pawelgabryelewicz/babel-preset-typescript-vue/pull/1#issuecomment-624412257

**Comment by pawelgabryelewicz** [comment]
Please update to 1.0.4, should be fixed.
